version: '3.8'
services:
  code-indexer:
    build: .
    container_name: indexer-${COMPOSE_PROJECT_NAME:-spotidal}
    volumes:
    - ../:/app
    environment:
    - PYTHONUNBUFFERED=1
    - PROJECT_NAME=${COMPOSE_PROJECT_NAME:-spotidal}
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    ports:
    - 127.0.0.1:${INDEXER_PORT:-9999}:9999
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - python3
      - -c
      - import os; exit(0 if os.path.exists('/app/.code_index.db') else 1)
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
    - indexing
networks:
  indexing:
    name: ${COMPOSE_PROJECT_NAME:-spotidal}-indexing
    driver: bridge
