version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.8.1
    container_name: qdrant-duplicate-prevention
    ports:
    - 6333:6333
    - 6334:6334
    volumes:
    - qdrant_storage:/qdrant/storage
    environment:
    - QDRANT__SERVICE__HTTP_PORT=6333
    - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6333/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
volumes:
  qdrant_storage:
    driver: local
